name: CI

on:
    push:
        branches: [ main ]
    pull_request:
    schedule:
        -   cron: '0 0 * * *'

jobs:
    check-cs:
        name: Check Coding Standards
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: --config=.php_cs --diff --dry-run

    tests:
        name: Test PHP ${{ matrix.php-version }} ${{ matrix.name }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '7.2', '7.3', '7.4', '8.0' ]
                composer-flags: [ '' ]
                name: [ '' ]
                include:
                    -   php-version: 7.2
                        composer-flags: '--prefer-lowest'
                        name: '(prefer lowest dependencies)'

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, xml

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ github.sha }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction ${{ matrix.composer-flags }}

            - name: Run tests
              run: php vendor/bin/simple-phpunit
              env:
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                  SLACK_TEST_CHANNEL: ${{ secrets.SLACK_TEST_CHANNEL }}
